# Generated by Django 2.2.4 on 2019-11-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placas', '0002_remove_cadastro_lote_qtd_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Req', models.CharField(choices=[('Nova', 'Nova'), ('Retorno', 'Retorno')], max_length=30, verbose_name='Tipo de requisicao')),
                ('Qtd_requerida', models.IntegerField(verbose_name='Qtd Requerida')),
                ('Qtd_atendida', models.IntegerField(default=0, editable=False, verbose_name='Qtd Atendida')),
                ('Status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado')], default='PendenteStatus', max_length=20)),
                ('Descricao', models.TextField(verbose_name='Descrição da requisição')),
                ('Data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('Data_alteracao_requisicao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CADASTRO_REQUISICAO',
            },
        ),
        migrations.CreateModel(
            name='Menu_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=199, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_REQUISICAO',
            },
        ),
        migrations.CreateModel(
            name='Item_requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100, verbose_name='Descrição do item')),
                ('Data_item', models.DateTimeField(auto_now_add=True)),
                ('Numero_serie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_placas_numero_serie', to='placas.Cadastro_placas', verbose_name='Número de Série')),
                ('Requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_requisicao_id', to='requisicao.Cadastro_Requisicao', verbose_name='Requisição')),
            ],
            options={
                'db_table': 'ITEM_REQUISICAO',
            },
        ),
    ]
