# Generated by Django 2.2.4 on 2019-10-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placas', '0008_auto_20191020_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=199, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_REQUISICAO',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Req', models.CharField(choices=[('Nova', 'Nova'), ('Retorno', 'Retorno')], max_length=30, verbose_name='Tipo de requisicao')),
                ('Qtd_placa', models.IntegerField(verbose_name='Qtd_de_Placas')),
                ('Status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status')),
                ('Lote_numero', models.ForeignKey(limit_choices_to={'Ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Cadastro_numero_lote', to='placas.Cadastro_lote')),
                ('Modelo', models.ForeignKey(limit_choices_to={'Ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modelo_placas_modelo', to='placas.Modelo_placas')),
            ],
        ),
    ]
