# Generated by Django 2.2.4 on 2019-12-02 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Req', models.CharField(choices=[('Nova', 'Nova'), ('Retorno', 'Retorno')], max_length=30, verbose_name='Tipo de requisicao')),
                ('Qtd_requerida', models.IntegerField(verbose_name='Qtd Requerida')),
                ('Qtd_atendida', models.IntegerField(default=0, editable=False, verbose_name='Qtd Atendida')),
                ('Status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado')], default='PendenteStatus', max_length=20)),
                ('Descricao', models.TextField(verbose_name='Descrição da requisição')),
                ('Data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('Data_alteracao_requisicao', models.DateTimeField(auto_now=True)),
                ('Modelo', models.ForeignKey(limit_choices_to={'Ativo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='Modelo_placas_modelo', to='placas.Modelo_placas')),
                ('username', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contas_usuario_username_requisicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CADASTRO_REQUISICAO',
            },
        ),
        migrations.CreateModel(
            name='Menu_Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=199, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_REQUISICAO',
            },
        ),
        migrations.CreateModel(
            name='Item_requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição do item')),
                ('Etapa_teste', models.CharField(blank=True, default='Pendente', max_length=20, null=True, verbose_name='Etapa do Teste')),
                ('Status_teste', models.CharField(blank=True, default='Pendente', max_length=20, null=True, verbose_name='Status do teste')),
                ('Situacao_teste', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Status do teste')),
                ('Data_item', models.DateTimeField(auto_now_add=True)),
                ('Numero_serie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_placas_numero_serie', to='placas.Cadastro_placas', verbose_name='Número de Série')),
                ('Requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_requisicao_id', to='requisicao.Cadastro_Requisicao', verbose_name='Requisição')),
                ('username', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_usuario_username_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ITEM_REQUISICAO',
            },
        ),
    ]
