# Generated by Django 2.2.4 on 2019-10-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_requisicao',
            name='Lote_numero',
        ),
    ]
