# Generated by Django 2.2.4 on 2019-11-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0002_auto_20191123_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_requisicao',
            name='Teste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testes.Teste', verbose_name='Teste'),
        ),
    ]
