# Generated by Django 2.2.4 on 2019-10-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0002_remove_cadastro_requisicao_lote_numero'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cadastro_requisicao',
            table='CADASTRO_REQUISICAO',
        ),
    ]
