# Generated by Django 2.2.4 on 2019-11-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0003_auto_20191123_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_requisicao',
            name='Teste',
        ),
        migrations.AddField(
            model_name='item_requisicao',
            name='Etapa_teste',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Etapa do Teste'),
        ),
        migrations.AddField(
            model_name='item_requisicao',
            name='Status_teste',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status do teste'),
        ),
    ]
