# Generated by Django 2.2.4 on 2019-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0004_auto_20191123_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_requisicao',
            name='Etapa_teste',
            field=models.CharField(blank=True, default='Burn In', max_length=20, null=True, verbose_name='Etapa do Teste'),
        ),
    ]
