# Generated by Django 2.2.4 on 2019-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0005_auto_20191129_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_requisicao',
            name='Status_teste',
            field=models.CharField(blank=True, default='Pendente', max_length=20, null=True, verbose_name='Status do teste'),
        ),
    ]
