# Generated by Django 2.2.4 on 2019-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0006_auto_20191130_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_requisicao',
            name='Descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição do item'),
        ),
    ]
