# Generated by Django 2.2.4 on 2019-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0007_auto_20191130_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_requisicao',
            name='Etapa_teste',
            field=models.CharField(blank=True, default='Pendente', max_length=20, null=True, verbose_name='Etapa do Teste'),
        ),
    ]
