# Generated by Django 2.2.4 on 2019-10-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0005_auto_20190928_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_placas',
            name='Modelo',
            field=models.ForeignKey(limit_choices_to={'Ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelo_placas_placas_modelo', to='placas.Modelo_placas'),
        ),
    ]
