# Generated by Django 2.2.4 on 2019-12-02 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_testes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=200, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_TESTES',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etapa_teste', models.CharField(choices=[('Pendente', 'Pendente'), ('Burn In', 'Burn In'), ('Pre-Teste', 'Pre-Teste'), ('Teste Final', 'Teste Final')], max_length=20, verbose_name='Etapa do teste')),
                ('Lote_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Lote')),
                ('Data_teste', models.DateTimeField(auto_now=True, verbose_name='Data Início')),
                ('Fim', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('Status', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status do Teste')),
                ('Situacao', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=20, verbose_name='Situação do teste')),
                ('Observacao', models.CharField(max_length=100, verbose_name='Observação')),
                ('Item_requisicao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requisicao_Item_Requisicao', to='requisicao.Item_requisicao')),
                ('username', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contas_usuario_username_teste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CADASTRO_TESTE',
            },
        ),
    ]
