# Generated by Django 2.2.4 on 2019-11-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_testes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=200, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_TESTES',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etapa_teste', models.CharField(choices=[('Burn In', 'Burn In'), ('Pre-Teste ', 'Pre-Teste'), ('Teste Final', 'Teste Final')], max_length=20, verbose_name='Etapa do teste')),
                ('Descricao', models.CharField(max_length=30, verbose_name='Teste de Burning')),
                ('Lote_numero', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('Inicio', models.DateTimeField(auto_now=True, verbose_name='Data Início')),
                ('Fim', models.DateTimeField(verbose_name='Data Fim')),
                ('Status', models.CharField(choices=[('Pedente', 'Pedente'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status Teste')),
                ('Situacao', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=20, verbose_name='Situaçao do teste')),
                ('Observacao', models.CharField(max_length=100, verbose_name='Observação')),
                ('Item_requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requisicao_Item_Requisicao', to='requisicao.Item_requisicao')),
            ],
            options={
                'db_table': 'CADASTRO_TESTE',
            },
        ),
    ]
