# Generated by Django 2.2.4 on 2019-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Fim',
            field=models.DateTimeField(blank=True, verbose_name='Data Fim'),
        ),
    ]
