# Generated by Django 2.2.4 on 2019-11-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_auto_20191123_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='Situacao',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=20, verbose_name='Situaçao do teste'),
        ),
    ]
