# Generated by Django 2.2.4 on 2019-11-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0004_auto_20191123_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Item_requisicao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requisicao_Item_Requisicao', to='requisicao.Item_requisicao'),
        ),
    ]
