# Generated by Django 2.2.4 on 2019-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0005_auto_20191123_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Lote_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Lote'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='Status',
            field=models.CharField(choices=[('Pedente', 'Pedente'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status Teste'),
        ),
    ]
