# Generated by Django 2.2.4 on 2019-11-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0006_auto_20191128_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status Teste'),
        ),
    ]
