# Generated by Django 2.2.4 on 2019-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0008_auto_20191129_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Etapa_teste',
            field=models.CharField(choices=[('Burn In', 'Burn In'), ('Pre-Teste', 'Pre-Teste'), ('Teste Final', 'Teste Final')], max_length=20, verbose_name='Etapa do teste'),
        ),
    ]
