# Generated by Django 2.2.4 on 2019-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0009_auto_20191129_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Status Teste'),
        ),
    ]
