# Generated by Django 2.2.4 on 2019-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0011_auto_20191130_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='Etapa_teste',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Burn In', 'Burn In'), ('Pre-Teste', 'Pre-Teste'), ('Teste Final', 'Teste Final')], max_length=20, verbose_name='Etapa do teste'),
        ),
    ]
