# Generated by Django 2.2.4 on 2019-12-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0012_auto_20191201_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='Inicio',
            new_name='Data_teste',
        ),
    ]
