# Generated by Django 2.2.4 on 2019-12-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testes', '0013_auto_20191201_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='username',
            field=models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_usuario_username_teste', to=settings.AUTH_USER_MODEL),
        ),
    ]
