# Generated by Django 2.2.4 on 2019-12-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0014_teste_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='username',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contas_usuario_username_teste', to=settings.AUTH_USER_MODEL),
        ),
    ]
